settings:
  APP_DISPLAY_NAME: ecclesias.Chat
  PRODUCTION_APP_NAME: ecclesias.Chat
  APP_GROUP_IDENTIFIER: group.net.ecclesias.chat
  BASE_BUNDLE_IDENTIFIER: net.ecclesias.chat
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: TC62G4GBN8