settings:
  APP_DISPLAY_NAME: ecclesias.Chat
  PRODUCTION_APP_NAME: ecclesias.Chat
  APP_GROUP_IDENTIFIER: group.net.ecclesias.chat
  BASE_BUNDLE_IDENTIFIER: net.ecclesias.chat
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: TC62G4GBN8

  # Optional configuration to load accounts from Element Classic.
  # CLASSIC_APP_GROUP_IDENTIFIER: group.im.vector
  # CLASSIC_APP_KEYCHAIN_SERVICE_IDENTIFIER: im.vector.app.encryption-manager-service
  # CLASSIC_APP_KEYCHAIN_ACCESS_GROUP_IDENTIFIER: "$(DEVELOPMENT_TEAM).im.vector.app.keychain.shared"
